from marshmallow import Schema
from marshmallow.fields import Date, Float, Integer, String


class IncidentGETRequest(Schema):
    ticken_id = String(length=12)
class IncidentPOSTRequest(Schema):
    incident_duration = Integer()
    platform_outage_duration = Integer()
    added_platform_outage_duration = Float()
    added_to_downtime = String(length=1)
    weekday = String(length=3)
    platform_impact_assessment = String(length=12)
    brief_description = String(length=512)
    root_cause = String(length=64)
    customer_impact = String(length=1024)

    cac_Website = Integer()
    cac_Login = Integer()
    cac_Trading_Platform = Integer()
    cac_Client_Deposit = Integer()
    cac_Client_Withdrawal = Integer()
    cac_Client_Access_Account = Integer()
    cac_Account_Opening = Integer()
    cac_Saleforce = Integer()
    cac_User_Pricing = Integer()
    cac_Internal_Hedging = Integer()
    cac_Internal_Reconciliation = Integer()

    im = String(length=12)
    pagerduty = String(length=32)
    jira_ticket = String(length=12)
    compliance_report = String(length=16)
    post_mortem = String(length=16)
    div1_OC = Integer()
    div2_OCAN = Integer()
    div3_OAP = Integer()
    div4_OEL = Integer()
    div5_UNKNOWN = Integer()
    div6_OCCORP = Integer()
    div7_OAPCFDs = Integer()
    div8_UNKNOWN = Integer()
    div9_OJ = Integer()
    div10_OJCFDs = Integer()
    div11_OAU = Integer()
    div12_OME = Integer()
    div13_OGM = Integer()
    com = String(length=16)
    compensation_paid = String(length=16)


class IncidentGETResponse(Schema):

    incident_duration = Integer()
    platform_outage_duration = Integer()
    added_platform_outage_duration = Float()
    added_to_downtime = String(length=1)
    weekday = String(length=3)
    platform_impact_assessment = String(length=12)
    brief_description = String(length=512)
    root_cause = String(length=64)
    customer_impact = String(length=1024)
    cac_Login = Integer()
    cac_Trading_Platform = Integer()
    cac_Client_Deposit = Integer()
    cac_Client_Withdrawal = Integer()
    cac_Client_Access_Account = Integer()
    cac_Account_Opening = Integer()
    cac_Saleforce = Integer()
    cac_User_Pricing = Integer()
    cac_Internal_Hedging = Integer()
    im = String(length=12)
    pagerduty = String(length=32)
    jira_ticket = String(length=12)
    compliance_report = String(length=16)
    post_mortem = String(length=16)
    div1_OC = Integer()
    div2_OCAN = Integer()
    div3_OAP = Integer()
    div4_OEL = Integer()
    div5_UNKNOWN = Integer()
    div6_OCCORP = Integer()
    div7_OAPCFDs = Integer()
    div8_UNKNOWN = Integer()
    div9_OJ = Integer()
    div10_OJCFDs = Integer()
    div11_OAU = Integer()
    div12_OME = Integer()
    div13_OGM = Integer()
    com = String(length=16)
    compensation_paid = String(length=16)
