---
application:
  securityContext:
    runAsUser: 1000

config:
  environment: UAT
  oauthClientId: 857866967765-660k938hd6hq879d66c2taberghfs4r1.apps.googleusercontent.com
  DB_HOST: sre-cloudsql-proxy
  DB_PORT: 3306
  DB_USERNAME: incident-management
  DB_DATABASE: incident-management
  DB_PASSWORD: imdb
  FLASK_SECRET: 1234567890
  JIRA_USERNAME: secret
  JIRA_PASSWORD: secret
databaseConnectionSecretName: incident-management-mysql-credentials
internalNginxIngress:
  cluster: k8s-uat-usc1
  environmentSuffix: u