orbs:
  container-release: oandacorp/container-release@8.7.0
  semantic-release: oandacorp/semantic-release@2.0.0
version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: bash scripts/citests.sh
      - store_test_results:
          path: results/pytest
      - store_artifacts:
          path: results/coverage

workflows:
  # Run integration builds/tests on all commits
  # Runs semantic release on commits to the mainline branch
  integration-build:
    jobs:
      - unit-test:
          context:
            - gcr
      - container-release/build-and-push-image:
          name: build-application-image
          context:
            - gcr
            - bitbucket-auth
            - snyk
          image: oanda-sre-im-db-backend
          extra-build-args: --build-arg PIP_EXTRA_INDEX_URL="https://_json_key_base64:$GCLOUD_SERVICE_KEY_BASE64@us-central1-python.pkg.dev/releaseinf/oanda-python-repo/simple/"
          push-image: false
          snyk-org: oanda-site-reliability-engineering
      - container-release/package-and-publish-helm-chart:
          name: package-application-helm-chart
          context:
            - gcr
            - bitbucket-auth
          chart-path: charts
          chart-name: sre-im-db-backend
      - semantic-release/node:
          requires:
            - build-application-image
            - package-application-helm-chart
            - unit-test
          context:
            - gcr
            - bitbucket-auth
          filters:
            branches:
              only:
                - main
  # Run build and publish on tags
  build-push-deploy:
    jobs:
      - container-release/build-and-push-image:
          name: build-and-push-application-image
          context:
            - gcr
            - bitbucket-auth
            - snyk
          image: oanda-sre-im-db-backend
          extra-build-args: --build-arg PIP_EXTRA_INDEX_URL="https://_json_key_base64:$GCLOUD_SERVICE_KEY_BASE64@us-central1-python.pkg.dev/releaseinf/oanda-python-repo/simple/"
          snyk-org: oanda-site-reliability-engineering
          filters: &tags-only
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - container-release/package-and-publish-helm-chart:
          name: package-and-publish-application-helm-chart
          context:
            - gcr
            - chartmuseum
            - bitbucket-auth
          chart-path: charts
          chart-name: sre-im-db-backend
          upload-to-chartmuseum: true
          filters: *tags-only
      - container-release/update-gitops-application:
          name: deploy-application-to-uat-environment
          requires:
            - build-and-push-application-image
            - package-and-publish-application-helm-chart
          context:
            - bitbucket-auth
          application: sre-im-db-backend
          folder: clusters/k8s/k8s-uat-usc1
          gitops-host: bitbucket.org
          gitops-org: oandacorp
          gitops-repo: argocd-deployments
          update-helm-chart: true
          filters: *tags-only