---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-config.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application-config.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  URL_PREFIX: {{ .Values.config.urlPrefix | quote }}
  OAUTH_CLIENT_ID: {{ .Values.config.oauthClientId | quote }}
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_USERNAME: {{ .Values.config.DB_USERNAME | quote }}
  DB_DATABASE: {{ .Values.config.DB_DATABASE | quote }}
  DB_PASSWORD: {{ .Values.config.DB_PASSWORD | quote }}
  FLASK_SECRET: {{ .Values.config.FLASK_SECRET | quote }}
  JIRA_USERNAME: {{ .Values.config.JIRA_USERNAME | quote }}
  JIRA_PASSWORD: {{ .Values.config.JIRA_PASSWORD | quote }}

