---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- if .Values.applicationService.annotations }}
  annotations:
    {{- toYaml .Values.applicationService.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.applicationService.type }}
  selector:
    {{- include "application.matchLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.applicationService.port }}
    name: http
    targetPort: {{ .Values.application.ports.application.name }}
    protocol: TCP
